"""remove password and switch to LTI

Revision ID: 8c764f844587
Revises: bbf99b17b878
Create Date: 2026-02-03 03:28:26.888469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c764f844587'
down_revision = 'bbf99b17b878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('helpcard_tag')
    op.drop_table('help_cards')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=50), nullable=True))

    op.create_table('help_cards',
    sa.Column('card_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('code', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='help_cards_ibfk_1'),
    sa.PrimaryKeyConstraint('card_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('helpcard_tag',
    sa.Column('help_card_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['help_card_id'], ['help_cards.card_id'], name=op.f('helpcard_tag_ibfk_1')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], name=op.f('helpcard_tag_ibfk_2')),
    sa.PrimaryKeyConstraint('help_card_id', 'tag_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
