"""add moodle_user_id and remove password

Revision ID: bbf99b17b878
Revises: 
Create Date: 2026-02-03 03:02:15.056845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbf99b17b878'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moodle_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.alter_column('mail',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_index(batch_op.f('mail'))
        batch_op.create_unique_constraint(None, ['moodle_user_id'])
        batch_op.drop_column('user_name')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('user_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('mail'), ['mail'], unique=True)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('mail',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('username')
        batch_op.drop_column('moodle_user_id')def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moodle_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.alter_column(
            'mail',
            existing_type=mysql.VARCHAR(length=50),
            type_=sa.String(length=255),
            existing_nullable=False
        )
        batch_op.alter_column(
            'role',
            existing_type=mysql.VARCHAR(length=50),
            nullable=True
        )
        batch_op.drop_index(batch_op.f('mail'))
        batch_op.create_unique_constraint(None, ['moodle_user_id'])
        batch_op.drop_column('user_name')
        batch_op.drop_column('password_hash')

    op.create_table('help_cards',
    sa.Column('card_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('code', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='help_cards_ibfk_1'),
    sa.PrimaryKeyConstraint('card_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('helpcard_tag',
    sa.Column('help_card_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['help_card_id'], ['help_cards.card_id'], name=op.f('helpcard_tag_ibfk_1')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], name=op.f('helpcard_tag_ibfk_2')),
    sa.PrimaryKeyConstraint('help_card_id', 'tag_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
